services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend:/app
    networks:
      - ecoheritage-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - ecoheritage-net

networks:
  ecoheritage-net:
    driver: bridge
