
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv

load_dotenv()

MONGO_URL = os.getenv("MONGODB_URL", "mongodb://localhost:27017")
DB_NAME = "ecoheritage"

FULL_SITES = [
    # --- NORTH INDIA ---
    {
        "id": "taj_mahal",
        "name": "Taj Mahal",
        "location": "Agra, Uttar Pradesh",
        "region": "north",
        "state": "uttar-pradesh",
        "image": "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
        "sustainability": 92,
        "crowd_level": "high",
        "rating": 4.9,
        "reviews": 35680,
        "best_time": "Oct-Mar",
        "description": "An immense mausoleum of white marble, built in Agra between 1631 and 1648 by order of the Mughal emperor Shah Jahan in memory of his favourite wife.",
        "eco_tips": ["Visit during off-peak hours", "Use electric vehicles", "Carry reusable bottles"],
        "entry_fee": 50,
        "coordinates": {"lat": 27.1751, "lng": 78.0421}
    },
    {
        "id": "agra_fort",
        "name": "Agra Fort",
        "location": "Agra, Uttar Pradesh",
        "region": "north",
        "state": "uttar-pradesh",
        "image": "http://localhost:8000/images/fort-agra-easy-peasy.jpg",
        "sustainability": 89,
        "crowd_level": "high",
        "rating": 4.7,
        "reviews": 12400,
        "best_time": "Oct-Mar",
        "description": "A powerful fortress of red sandstone, encompassing the imperial city of the Mughal rulers. It comprises many fairy-tale palaces, such as the Jahangir Palace and the Khas Mahal.",
        "eco_tips": ["Walk between monuments", "Avoid single-use plastics"],
        "entry_fee": 50,
        "coordinates": {"lat": 27.1795, "lng": 78.0211}
    },
    {
        "id": "fatehpur_sikri",
        "name": "Fatehpur Sikri",
        "location": "Agra District, Uttar Pradesh",
        "region": "north",
        "state": "uttar-pradesh",
        "image": "https://static.wixstatic.com/media/055605_5c2549f84a254d18b7eddf99afe12ff2~mv2.png/v1/fill/w_572,h_324,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/fdc7ba38-f616-41e4-a536-c85db0cc6bcc15.png",
        "sustainability": 85,
        "crowd_level": "medium",
        "rating": 4.6,
        "reviews": 8900,
        "best_time": "Oct-Mar",
        "description": "Built during the second half of the 16th century by the Emperor Akbar, Fatehpur Sikri (the City of Victory) was the capital of the Mughal Empire for only some 10 years.",
        "eco_tips": ["Respect local guides", "Dispose of waste responsibly"],
        "entry_fee": 40,
        "coordinates": {"lat": 27.0945, "lng": 77.6679}
    },
    {
        "id": "humayuns_tomb",
        "name": "Humayun's Tomb",
        "location": "New Delhi",
        "region": "north",
        "state": "delhi",
        "image": "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800",
        "sustainability": 90,
        "crowd_level": "medium",
        "rating": 4.8,
        "reviews": 15600,
        "best_time": "Oct-Mar",
        "description": "This tomb, built in 1570, is of particular cultural significance as it was the first garden-tomb on the Indian subcontinent.",
        "eco_tips": ["Use Delhi Metro (Violet Line)", "Carry your own water bottle"],
        "entry_fee": 40,
        "coordinates": {"lat": 28.5933, "lng": 77.2507}
    },
    {
        "id": "qutub_minar",
        "name": "Qutub Minar",
        "location": "New Delhi",
        "region": "north",
        "state": "delhi",
        "image": "https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/6811a27cdb9e31001dc78146.jpg",
        "sustainability": 88,
        "crowd_level": "high",
        "rating": 4.7,
        "reviews": 21000,
        "best_time": "Oct-Mar",
        "description": "Built in the early 13th century a few kilometres south of Delhi, the red sandstone tower of Qutb Minar is 72.5 m high.",
        "eco_tips": ["Use public transport", "Do not litter in the complex"],
        "entry_fee": 40,
        "coordinates": {"lat": 28.5244, "lng": 77.1855}
    },
    {
        "id": "red_fort",
        "name": "Red Fort",
        "location": "New Delhi",
        "region": "north",
        "state": "delhi",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Red_Fort%2C_Delhi_by_alexfurr.jpg/960px-Red_Fort%2C_Delhi_by_alexfurr.jpg",
        "sustainability": 85,
        "crowd_level": "high",
        "rating": 4.6,
        "reviews": 18500,
        "best_time": "Oct-Mar",
        "description": "The Red Fort Complex was built as the palace fort of Shahjahanabad – the new capital of the fifth Mughal Emperor of India, Shah Jahan.",
        "eco_tips": ["Use the Metro (Red Line)", "Avoid plastic bags"],
        "entry_fee": 35,
        "coordinates": {"lat": 28.6562, "lng": 77.2410}
    },
    {
        "id": "jantar_mantar",
        "name": "Jantar Mantar",
        "location": "Jaipur, Rajasthan",
        "region": "north",
        "state": "rajasthan",
        "image": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800",
        "sustainability": 93,
        "crowd_level": "medium",
        "rating": 4.5,
        "reviews": 9200,
        "best_time": "Oct-Mar",
        "description": "The Jantar Mantar, in Jaipur, is an astronomical observation site built in the early 18th century.",
        "eco_tips": ["Learn about ancient astronomy", "Protect the instruments"],
        "entry_fee": 200,
        "coordinates": {"lat": 26.9248, "lng": 75.8246}
    },
    {
        "id": "amber_fort",
        "name": "Amber Fort",
        "location": "Jaipur, Rajasthan",
        "region": "north",
        "state": "rajasthan",
        "image": "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=800",
        "sustainability": 89,
        "crowd_level": "high",
        "rating": 4.8,
        "reviews": 22300,
        "best_time": "Oct-Mar",
        "description": "Startlingly beautiful red sandstone and marble fort, part of the Hill Forts of Rajasthan.",
        "eco_tips": ["Avoid elephant rides (walk or jeep)", "Conserve water"],
        "entry_fee": 500,
        "coordinates": {"lat": 26.9855, "lng": 75.8513}
    },
    {
        "id": "keoladeo",
        "name": "Keoladeo National Park",
        "location": "Bharatpur, Rajasthan",
        "region": "north",
        "state": "rajasthan",
        "image": "https://images.hindustantimes.com/rf/image_size_630x354/HT/p2/2017/04/03/Pictures/knp-in-bharatpur-ht-file-photo_1a7ffd54-1881-11e7-8dd7-d947b0232760.JPG",
        "sustainability": 97,
        "crowd_level": "medium",
        "rating": 4.6,
        "reviews": 4500,
        "best_time": "Aug-Nov",
        "description": "Formerly a duck-hunting reserve of the Maharajas, Keoladeo is a major wintering area for large numbers of aquatic birds.",
        "eco_tips": ["Rent a cycle inside", "Maintain silence for birds"],
        "entry_fee": 75,
        "coordinates": {"lat": 27.1592, "lng": 77.5232}
    },
     {
        "id": "valley_of_flowers",
        "name": "Valley of Flowers",
        "location": "Uttarakhand",
        "region": "north",
        "state": "uttarakhand",
        "image": "http://localhost:8000/images/valleyofflowers.png",
        "sustainability": 99,
        "crowd_level": "low",
        "rating": 4.9,
        "reviews": 4200,
        "best_time": "Jul-Sep",
        "description": "A high-altitude Himalayan valley with endemic alpine flowers and diverse fauna.",
        "eco_tips": ["Strictly no plastic", "Pack out all trash"],
        "entry_fee": 150,
        "coordinates": {"lat": 30.7280, "lng": 79.6053}
    },
    {
        "id": "nanda_devi",
        "name": "Nanda Devi National Park",
        "location": "Uttarakhand",
        "region": "north",
        "state": "uttarakhand",
        "image": "https://img-cdn.publive.online/fit-in/1200x675/local-samosal/media/media_files/2025/02/13/XKNjHrb5czmh2jeauAez.png",
        "sustainability": 98,
        "crowd_level": "low",
        "rating": 4.8,
        "reviews": 1200,
        "best_time": "May-Oct",
        "description": "Dominated by the 7,817 m peak of Nanda Devi, India's second highest mountain.",
        "eco_tips": ["Treking permits required", "Leave no trace"],
        "entry_fee": 150,
        "coordinates": {"lat": 30.4035, "lng": 79.9926}
    },
     {
        "id": "great_himalayan",
        "name": "Great Himalayan National Park",
        "location": "Kullu, Himachal Pradesh",
        "region": "north",
        "state": "himachal-pradesh",
        "image": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800",
        "sustainability": 96,
        "crowd_level": "low",
        "rating": 4.7,
        "reviews": 1800,
        "best_time": "Apr-Jun, Sep-Nov",
        "description": "Characterized by high alpine peaks, alpine meadows and riverine forests.",
        "eco_tips": ["Camp responsibly", "Support local homestays"],
        "entry_fee": 100,
        "coordinates": {"lat": 31.7289, "lng": 77.5817}
    },
     {
        "id": "kalka_shimla",
        "name": "Kalka-Shimla Railway",
        "location": "Himachal Pradesh",
        "region": "north",
        "state": "himachal-pradesh",
        "image": "https://images.hindustantimes.com/img/2024/08/21/1600x900/GVfInyOaMAIY7VI_1724236326702_1724236344885.jpg",
        "sustainability": 91,
        "crowd_level": "medium",
        "rating": 4.7,
        "reviews": 8900,
        "best_time": "Mar-Jun",
        "description": "A 96-km narrow-gauge railway built in the mid-19th century, climbing from the plains to Shimla.",
        "eco_tips": ["Book tickets in advance", "Do not throw waste on tracks"],
        "entry_fee": 300,
        "coordinates": {"lat": 30.8350, "lng": 76.9350}
    },

    # --- SOUTH INDIA ---
    {
        "id": "hampi",
        "name": "Hampi Ruins",
        "location": "Hampi, Karnataka",
        "region": "south",
        "state": "karnataka",
        "image": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800",
        "sustainability": 94,
        "crowd_level": "medium",
        "rating": 4.9,
        "reviews": 24500,
        "best_time": "Oct-Feb",
        "description": "The austere, grandiose site of Hampi was the last capital of the last great Hindu Kingdom of Vijayanagar.",
        "eco_tips": ["Rent bicycles", "Stay in eco-lodges", "Respect archaeological sites"],
        "entry_fee": 40,
        "coordinates": {"lat": 15.3350, "lng": 76.4600}
    },
    {
        "id": "pattadakal",
        "name": "Pattadakal Monuments",
        "location": "Bagalkot, Karnataka",
        "region": "south",
        "state": "karnataka",
        "image": "https://www.storiesbysoumya.com/wp-content/uploads/2018/11/20181117-DSC_0254-min.jpg",
        "sustainability": 92,
        "crowd_level": "low",
        "rating": 4.6,
        "reviews": 3200,
        "best_time": "Oct-Mar",
        "description": "It represents the high point of an eclectic art which, in the 7th and 8th centuries, achieved a harmonious blend of architectural forms.",
        "eco_tips": ["Hire government approved guides", "Combine with Badami and Aihole"],
        "entry_fee": 40,
        "coordinates": {"lat": 15.9496, "lng": 75.8159}
    },
    {
        "id": "brihadisvara",
        "name": "Brihadisvara Temple",
        "location": "Thanjavur, Tamil Nadu",
        "region": "south",
        "state": "tamil-nadu",
        "image": "https://www.templewalks.com/wp-content/uploads/2025/06/Brihadeeswarar-temple.png",
        "sustainability": 91,
        "crowd_level": "medium",
        "rating": 4.9,
        "reviews": 15600,
        "best_time": "Nov-Mar",
        "description": "Known as the Big Temple, this is one of the Great Living Chola Temples, built by Raja Raja Chola I.",
        "eco_tips": ["Remove footwear outside", "Respect religious customs"],
        "entry_fee": 0,
        "coordinates": {"lat": 10.7828, "lng": 79.1318}
    },
     {
        "id": "mahabalipuram",
        "name": "Mahabalipuram",
        "location": "Mahabalipuram, Tamil Nadu",
        "region": "south",
        "state": "tamil-nadu",
        "image": "https://images.squarespace-cdn.com/content/v1/6298cb774cf3830bc9b342bf/60d4051c-a6e4-45a4-91d3-912542162244/descent-ganga-carving-mahabalipuram.jpg",
        "sustainability": 89,
        "crowd_level": "medium",
        "rating": 4.7,
        "reviews": 18900,
        "best_time": "Nov-Feb",
        "description": "Group of Sanctuaries founded by the Pallava kings, carved out of rock along the Coromandel coast.",
        "eco_tips": ["Keep the beach clean", "Use electric buggies if available"],
        "entry_fee": 40,
        "coordinates": {"lat": 12.6208, "lng": 80.1945}
    },
    {
        "id": "nilgiri_mountain_railway",
        "name": "Nilgiri Mountain Railway",
        "location": "Ooty, Tamil Nadu",
        "region": "south",
        "state": "tamil-nadu",
        "image": "https://travel-along.in/wp-content/uploads/2024/03/photo-size.jpg?w=852",
        "sustainability": 92,
        "crowd_level": "high",
        "rating": 4.6,
        "reviews": 11000,
        "best_time": "All year",
        "description": "This railway, scaling the Blue Mountains, is a legacy of the colonial era and a marvel of engineering.",
        "eco_tips": ["Enjoy the slow travel", "No plastic on board"],
        "entry_fee": 205,
        "coordinates": {"lat": 11.4102, "lng": 76.6950}
    },
    {
        "id": "western_ghats",
        "name": "Western Ghats",
        "location": "Multiple States (South/West)",
        "region": "south",
        "state": "kerala",
        "image": "https://images.unsplash.com/photo-1593181629936-11c609b8db9b?w=800",
        "sustainability": 96,
        "crowd_level": "medium",
        "rating": 4.9,
        "reviews": 5600,
        "best_time": "Sep-Mar",
        "description": "Older than the Himalaya mountains, the mountain chain of the Western Ghats represents geomorphic features of immense importance.",
        "eco_tips": ["Support biodiversity conservation", "Stay in homestays"],
        "entry_fee": 50,
        "coordinates": {"lat": 10.1500, "lng": 77.1600}
    },

    # --- WEST INDIA ---
    {
        "id": "ajanta_caves",
        "name": "Ajanta Caves",
        "location": "Aurangabad, Maharashtra",
        "region": "west",
        "state": "maharashtra",
        "image": "https://www.indianluxurytrains.com/wp-content/uploads/2020/12/Ajanta-Caves-Maharashtra.jpg",
        "sustainability": 93,
        "crowd_level": "medium",
        "rating": 4.9,
        "reviews": 16500,
        "best_time": "Nov-Feb",
        "description": "Ancient Buddhist cave monuments with paintings and sculptures which are masterpieces of Buddhist religious art.",
        "eco_tips": ["No flash photography", "Maintain silence"],
        "entry_fee": 40,
        "coordinates": {"lat": 20.5519, "lng": 75.7033}
    },
    {
        "id": "ellora_caves",
        "name": "Ellora Caves",
        "location": "Aurangabad, Maharashtra",
        "region": "west",
        "state": "maharashtra",
        "image": "https://maharashtratourism.gov.in/wp-content/uploads/2024/11/ELLORA-CAVES-2.jpg",
        "sustainability": 92,
        "crowd_level": "medium",
        "rating": 4.9,
        "reviews": 18200,
        "best_time": "Nov-Feb",
        "description": "34 monasteries and temples, carved side by side in the wall of a high basalt cliff.",
        "eco_tips": ["Wear comfortable walking shoes", "Carry water"],
        "entry_fee": 40,
        "coordinates": {"lat": 20.0258, "lng": 75.1772}
    },
    {
        "id": "elephanta_caves",
        "name": "Elephanta Caves",
        "location": "Mumbai, Maharashtra",
        "region": "west",
        "state": "maharashtra",
        "image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/ac/59/5c/caption.jpg?w=900&h=-1&s=1",
        "sustainability": 90,
        "crowd_level": "high",
        "rating": 4.5,
        "reviews": 14300,
        "best_time": "Nov-Mar",
        "description": "The City of Caves on an island in the Sea of Oman close to Bombay, contains a collection of rock art linked to the cult of Shiva.",
        "eco_tips": ["Take the ferry responsibly", "Avoid feeding monkeys"],
        "entry_fee": 40,
        "coordinates": {"lat": 18.9633, "lng": 72.9315}
    },
    {
        "id": "cst_station",
        "name": "Chhatrapati Shivaji Terminus",
        "location": "Mumbai, Maharashtra",
        "region": "west",
        "state": "maharashtra",
        "image": "https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=800",
        "sustainability": 88,
        "crowd_level": "high",
        "rating": 4.7,
        "reviews": 25000,
        "best_time": "All year",
        "description": "An outstanding example of Victorian Gothic Revival architecture in India, blended with themes deriving from Indian traditional architecture.",
        "eco_tips": ["Use local trains", "Respect the busy commuters"],
        "entry_fee": 0,
        "coordinates": {"lat": 18.9400, "lng": 72.8353}
    },
    {
        "id": "rani_ki_vav",
        "name": "Rani-ki-Vav",
        "location": "Patan, Gujarat",
        "region": "west",
        "state": "gujarat",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSk6Rrus3dx-OnKfbZu67o010IfqILrNMvv8A&s",
        "sustainability": 93,
        "crowd_level": "medium",
        "rating": 4.8,
        "reviews": 6500,
        "best_time": "Oct-Mar",
        "description": "An exceptional example of a distinctive form of subterranean water architecture of the Indian subcontinent.",
        "eco_tips": ["Keep the area clean", "Hire a local guide"],
        "entry_fee": 40,
        "coordinates": {"lat": 23.8589, "lng": 72.1025}
    },
    {
        "id": "goa_churches",
        "name": "Churches and Convents of Goa",
        "location": "Velha Goa, Goa",
        "region": "west",
        "state": "goa",
        "image": "https://www.fabhotels.com/blog/wp-content/uploads/2018/07/featureImage600x400.jpg",
        "sustainability": 89,
        "crowd_level": "high",
        "rating": 4.6,
        "reviews": 19000,
        "best_time": "Nov-Feb",
        "description": "The churches and convents of Goa, the former capital of the Portuguese Indies, illustrate the evangelization of Asia.",
        "eco_tips": ["Respect religious sites", "Dress modestly"],
        "entry_fee": 0,
        "coordinates": {"lat": 15.5024, "lng": 73.9116}
    },
     {
        "id": "dholavira",
        "name": "Dholavira",
        "location": "Kutch, Gujarat",
        "region": "west",
        "state": "gujarat",
        "image": "https://www.trawell.in/admin/images/upload/359804533Dholavira.jpg",
        "sustainability": 95,
        "crowd_level": "low",
        "rating": 4.7,
        "reviews": 1100,
        "best_time": "Nov-Mar",
        "description": "The ancient Harappan city of Dholavira, one of the most remarkable and well-preserved urban settlements in South Asia.",
        "eco_tips": ["Carry water", "Do not disturb ruins"],
        "entry_fee": 0,
        "coordinates": {"lat": 23.8821, "lng": 70.2126}
    },


    # --- CENTRAL INDIA ---
    {
        "id": "khajuraho",
        "name": "Khajuraho Temples",
        "location": "Madhya Pradesh",
        "region": "central",
        "state": "madhya-pradesh",
        "image": "https://www.andbeyond.com/wp-content/uploads/sites/5/khajuraho-india-temple-complex.jpg",
        "sustainability": 91,
        "crowd_level": "medium",
        "rating": 4.8,
        "reviews": 13200,
        "best_time": "Oct-Feb",
        "description": "These temples are a striking balance between architecture and sculpture, famous for their Nagara-style architectural symbolism and erotic sculptures.",
        "eco_tips": ["Use local transport", "Support local artisans"],
        "entry_fee": 40,
        "coordinates": {"lat": 24.8318, "lng": 79.9199}
    },
    {
        "id": "sanchi_stupa",
        "name": "Sanchi Stupa",
        "location": "Madhya Pradesh",
        "region": "central",
        "state": "madhya-pradesh",
        "image": "https://images.unsplash.com/photo-1623944889288-cd147dbb517c?w=800",
        "sustainability": 94,
        "crowd_level": "low",
        "rating": 4.8,
        "reviews": 8500,
        "best_time": "Oct-Mar",
        "description": "Buddhist monuments that date back to the 2nd and 1st centuries B.C., the oldest Buddhist sanctuary in existence.",
        "eco_tips": ["Quiet contemplation", "Maintain cleanliness"],
        "entry_fee": 30,
        "coordinates": {"lat": 23.4792, "lng": 77.7377}
    },
    {
        "id": "bhimbetka",
        "name": "Bhimbetka Rock Shelters",
        "location": "Madhya Pradesh",
        "region": "central",
        "state": "madhya-pradesh",
        "image": "https://s7ap1.scene7.com/is/image/incredibleindia/bhimbetka-rock-shelters-bhopal-madhya-pradesh-1-attr-hero?qlt=82&ts=1742167436321",
        "sustainability": 95,
        "crowd_level": "low",
        "rating": 4.6,
        "reviews": 3200,
        "best_time": "Oct-Mar",
        "description": "The Rock Shelters of Bhimbetka are in the foothills of the Vindhyan Mountains, exhibiting the earliest traces of human life in India.",
        "eco_tips": ["Do not touch paintings", "Stay on marked paths"],
        "entry_fee": 25,
        "coordinates": {"lat": 22.9328, "lng": 77.6186}
    },

    # --- EAST & NORTHEAST INDIA ---
    {
        "id": "konark_sun_temple",
        "name": "Sun Temple, Konark",
        "location": "Konark, Odisha",
        "region": "east",
        "state": "odisha",
        "image": "https://i0.wp.com/thewanderingcore.com/wp-content/uploads/2017/03/img_3367.jpg?resize=750%2C565&ssl=1",
        "sustainability": 92,
        "crowd_level": "medium",
        "rating": 4.8,
        "reviews": 17800,
        "best_time": "Oct-Feb",
        "description": "On the shores of the Bay of Bengal, the temple is a monumental representation of the sun god Surya's chariot.",
        "eco_tips": ["Avoid plastic on beach", "Respect local culture"],
        "entry_fee": 40,
        "coordinates": {"lat": 19.8876, "lng": 86.0945}
    },
    {
        "id": "sundarbans",
        "name": "Sundarbans National Park",
        "location": "West Bengal",
        "region": "east",
        "state": "west-bengal",
        "image": "https://sundarbanlokenathtravels.com/assets/uploads/022023/large/sundarban_park_.jpg",
        "sustainability": 96,
        "crowd_level": "low",
        "rating": 4.5,
        "reviews": 2100,
        "best_time": "Sep-Mar",
        "description": "The largest mangrove forest in the world, and home to the Royal Bengal Tiger.",
        "eco_tips": ["Silence zones", "No plastic disposal in river"],
        "entry_fee": 60,
        "coordinates": {"lat": 21.9497, "lng": 88.8995}
    },
    {
        "id": "kaziranga",
        "name": "Kaziranga National Park",
        "location": "Assam",
        "region": "northeast",
        "state": "assam",
        "image": "https://www.andbeyond.com/wp-content/uploads/sites/5/one-horned-rhino-kaziranga-national-park.jpg",
        "sustainability": 97,
        "crowd_level": "medium",
        "rating": 4.8,
        "reviews": 5600,
        "best_time": "Nov-Apr",
        "description": "In the heart of Assam, this park is inhabited by the world's largest population of one-horned rhinoceroses.",
        "eco_tips": ["Book jeep safari in advance", "Do not disturb wildlife"],
        "entry_fee": 100,
        "coordinates": {"lat": 26.5775, "lng": 93.1711}
    },
    {
        "id": "manas",
        "name": "Manas Wildlife Sanctuary",
        "location": "Assam",
        "region": "northeast",
        "state": "assam",
        "image": "https://i0.wp.com/kaziranganationalparkassam.in/wp-content/uploads/2018/08/manas-np-entry-point-at-banasbari-range.jpg?resize=648%2C414&ssl=1",
        "sustainability": 95,
        "crowd_level": "low",
        "rating": 4.6,
        "reviews": 1500,
        "best_time": "Nov-Apr",
        "description": "On a gentle slope in the foothills of the Himalayas, Manas is home to a great variety of wildlife, including many endangered species.",
        "eco_tips": ["Stay in eco-chambres", "Support local conservation efforts"],
        "entry_fee": 50,
        "coordinates": {"lat": 26.7118, "lng": 90.9333}
    },
    {
        "id": "mahabodhi",
        "name": "Mahabodhi Temple Complex",
        "location": "Bodh Gaya, Bihar",
        "region": "east",
        "state": "bihar",
        "image": "https://www.tourmyindia.com/heritage/images/mahabodhi-bodhgaya1.jpg",
        "sustainability": 91,
        "crowd_level": "high",
        "rating": 4.8,
        "reviews": 11000,
        "best_time": "Oct-Mar",
        "description": "One of the four holy sites related to the life of the Lord Buddha, and particularly to the attainment of Enlightenment.",
        "eco_tips": ["Respect the meditation zones", "Keep the complex clean"],
        "entry_fee": 0,
        "coordinates": {"lat": 24.6959, "lng": 84.9914}
    },
    {
        "id": "champaner_pavagadh",
        "name": "Champaner-Pavagadh Park",
        "location": "Gujarat",
        "region": "west",
        "state": "gujarat",
        "image": "https://img-cdn.publive.online/fit-in/1200x675/local-samosal/media/media_files/2025/04/17/YR0XbPqLVLhIuLGjS3Jx.jpg",
        "sustainability": 92,
        "crowd_level": "low",
        "rating": 4.6,
        "reviews": 3400,
        "best_time": "Oct-Feb",
        "description": "A concentration of largely unexcavated archaeological, historic and living cultural heritage properties.",
        "eco_tips": ["Wear good walking shoes", "Carry water"],
        "entry_fee": 40,
        "coordinates": {"lat": 22.4862, "lng": 73.5229}
     },
    # --- RECENT ADDITIONS & MISSING SITES ---
    {
        "id": "moidams",
        "name": "Moidams of the Ahom Dynasty",
        "location": "Charaideo, Assam",
        "region": "northeast",
        "state": "assam",
        "image": "https://chalohoppo.com/wp-content/uploads/2025/04/1-1-1024x576.jpg",
        "sustainability": 93,
        "crowd_level": "low",
        "rating": 4.8,
        "reviews": 500,
        "best_time": "Oct-Mar",
        "description": "Added in 2024. The mound-burial system of the Ahom dynasty, reflecting their unique funerary traditions.",
        "eco_tips": ["Respect the sacred grounds", "Maintain silence"],
        "entry_fee": 25,
        "coordinates": {"lat": 26.9634, "lng": 94.8690}
    },
    {
        "id": "maratha_forts",
        "name": "Maratha Military Landscapes",
        "location": "Maharashtra",
        "region": "west",
        "state": "maharashtra",
        "image": "https://static.tripzilla.in/media/48395/conversions/3e20b031-c98a-49d0-be49-fa2e48ecdb49-w768.webp",
        "sustainability": 91,
        "crowd_level": "medium",
        "rating": 4.9,
        "reviews": 8500,
        "best_time": "Jun-Feb",
        "description": "Added in 2025. A network of forts (Salher, Shivneri, Raigad, etc.) exhibiting the unique military architecture of the Maratha rulers.",
        "eco_tips": ["Carry trash back", "Safe trekking gear required"],
        "entry_fee": 25,
        "coordinates": {"lat": 18.2346, "lng": 73.4426}
    },
    {
        "id": "santiniketan",
        "name": "Santiniketan",
        "location": "West Bengal",
        "region": "east",
        "state": "west-bengal",
        "image": "https://assets.cntraveller.in/photos/60ba1e65e1b212c19a817cea/master/w_1600%2Cc_limit/Bengal-tagore.jpg",
        "sustainability": 95,
        "crowd_level": "medium",
        "rating": 4.7,
        "reviews": 4200,
        "best_time": "Aug-Mar",
        "description": "Established by Nobel laureate Rabindranath Tagore, this university town represents a unique pedagogical approach closer to nature.",
        "eco_tips": ["Cycle around the campus", "Attend cultural events"],
        "entry_fee": 0,
        "coordinates": {"lat": 23.6749, "lng": 87.6896}
    },
    {
        "id": "hoysala_temples",
        "name": "Sacred Ensembles of the Hoysalas",
        "location": "Belur/Halebidu, Karnataka",
        "region": "south",
        "state": "karnataka",
        "image": "https://i.ytimg.com/vi/o2BfAqjWPZQ/sddefault.jpg",
        "sustainability": 92,
        "crowd_level": "medium",
        "rating": 4.9,
        "reviews": 9800,
        "best_time": "Oct-Mar",
        "description": "Exquisite soapstone temples at Belur, Halebidu, and Somanathapura, known for intricate carvings.",
        "eco_tips": ["No footwear inside", "Use local guides"],
        "entry_fee": 40,
        "coordinates": {"lat": 13.1623, "lng": 75.8596}
    },
     {
        "id": "ramappa_temple",
        "name": "Kakatiya Rudreshwara (Ramappa) Temple",
        "location": "Telangana",
        "region": "south",
        "state": "telangana",
        "image": "https://tadvai.feriadoresorts.com/wp-content/uploads/2022/08/kakatiya-rudreshwara-ramappa-temple-ramappa-temple.jpg",
        "sustainability": 90,
        "crowd_level": "low",
        "rating": 4.8,
        "reviews": 3100,
        "best_time": "Oct-Feb",
        "description": "A masterpiece of Kakatiya style art, featuring floating bricks and intricate carvings.",
        "eco_tips": ["Respect the heritage", "Keep premises clean"],
        "entry_fee": 25,
        "coordinates": {"lat": 18.2599, "lng": 79.9439}
    },
    {
        "id": "ahmedabad",
        "name": "Historic City of Ahmadabad",
        "location": "Ahmedabad, Gujarat",
        "region": "west",
        "state": "gujarat",
        "image": "https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/ahmedabad_647_070917020032.jpg",
        "sustainability": 86,
        "crowd_level": "high",
        "rating": 4.6,
        "reviews": 12500,
        "best_time": "Oct-Mar",
        "description": "The first UNESCO World Heritage City in India, founded by Sultan Ahmad Shah in the 15th century.",
        "eco_tips": ["Heritage walk", "Visit textile museum"],
        "entry_fee": 0,
        "coordinates": {"lat": 23.0225, "lng": 72.5714}
    },
    {
        "id": "jaipur_city",
        "name": "Jaipur City",
        "location": "Jaipur, Rajasthan",
        "region": "north",
        "state": "rajasthan",
        "image": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800",
        "sustainability": 88,
        "crowd_level": "high",
        "rating": 4.7,
        "reviews": 28000,
        "best_time": "Oct-Mar",
        "description": "The Pink City, founded in 1727, known for its grid plan and iconic architecture like Hawa Mahal.",
        "eco_tips": ["Use e-rickshaws", "Buy local handicrafts"],
        "entry_fee": 0,
        "coordinates": {"lat": 26.9124, "lng": 75.7873}
    },
    {
        "id": "nalanda",
        "name": "Nalanda Mahavihara",
        "location": "Nalanda, Bihar",
        "region": "east",
        "state": "bihar",
        "image": "https://www.buddhisttourism.online/assets/images/nalanda-main.webp",
        "sustainability": 93,
        "crowd_level": "medium",
        "rating": 4.8,
        "reviews": 7600,
        "best_time": "Oct-Mar",
        "description": "Archaeological Site of Nalanda Mahavihara comprises the scholastic and monastic institutional remains of a monastic and scholastic institution.",
        "eco_tips": ["Educational tours", "Silence in ruins"],
        "entry_fee": 40,
        "coordinates": {"lat": 25.1357, "lng": 85.4455}
    },
     {
        "id": "capitol_complex",
        "name": "The Architectural Work of Le Corbusier",
        "location": "Chandigarh",
        "region": "north",
        "state": "chandigarh",
        "image": "https://culturetourist.com/wp-content/uploads/2022/09/Photo-by-Ricardo-Gomez-Angel-on-Unsplash.jpeg",
        "sustainability": 91,
        "crowd_level": "low",
        "rating": 4.5,
        "reviews": 2300,
        "best_time": "Oct-Mar",
        "description": "Capitol Complex in Chandigarh, part of Le Corbusier's outstanding contribution to the Modern Movement.",
        "eco_tips": ["Guided architecture tours", "Respect government offices"],
        "entry_fee": 0,
        "coordinates": {"lat": 30.7590, "lng": 76.8041}
    },
     {
        "id": "khangchendzonga",
        "name": "Khangchendzonga National Park",
        "location": "Sikkim",
        "region": "northeast",
        "state": "sikkim",
        "image": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH5bs0uR2AG-f6sZc8-LHuF17EExq2SEmFINb2BA92HWXQdqmhpaHBET_LRGqwj_Opq7kTJ6Zs_jpBG7SJ94CYdZnN4tAFZrrg1m1kFV-qdzhvEEObsh3ppJFO84uF-xlP2ukb2=w270-h312-n-k-no",
        "sustainability": 99,
        "crowd_level": "low",
        "rating": 4.9,
        "reviews": 1800,
        "best_time": "Mar-May, Sep-Nov",
        "description": "India's only Mixed Heritage Site. Located in the heart of the Himalayas in Sikkim.",
        "eco_tips": ["Strictly organic state", "Leave no trace"],
        "entry_fee": 350,
        "coordinates": {"lat": 27.7025, "lng": 88.1475}
    },
     {
        "id": "darjeeling_railway",
        "name": "Darjeeling Himalayan Railway",
        "location": "West Bengal",
        "region": "east",
        "state": "west-bengal",
        "image": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhukDB6KgkW_3p7qt9uZ1WpxW8wcxj2vICZW1MZNfo7JPYWs7-k0v21pEySwqqreCWSGlpMeLxCldrOY9EjTF6u50hLDuRcbQppcXpqBbdrCi29UQZwBU4Hnmhcrc6-efi72Lymug6wtwfB/w1200-h630-p-k-no-nu/Darjeeling+Himalayan+Railway+Toy+Train.jpg",
        "sustainability": 90,
        "crowd_level": "high",
        "rating": 4.6,
        "reviews": 14500,
        "best_time": "Mar-Jun, Sep-Dec",
        "description": "The first hill passenger railway. Known as the 'Toy Train', offering breathtaking views of the Himalayas.",
        "eco_tips": ["Steam engine heritage", "Don't litter on tracks"],
        "entry_fee": 100,
        "coordinates": {"lat": 27.0374, "lng": 88.2627}
    }
]


async def seed_heritage():
    print(f"Connecting to MongoDB at {MONGO_URL}...")
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    
    print("Clearing and Seeding Heritage Sites...")
    
    # Clear existing
    await db.heritage_sites.delete_many({})
    
    # Insert new
    result = await db.heritage_sites.insert_many(FULL_SITES)
    
    # Create Indices
    await db.heritage_sites.create_index([("name", "text"), ("location", "text"), ("description", "text")])
    await db.heritage_sites.create_index([("region", 1)])
    await db.heritage_sites.create_index([("sustainability", -1)])
    print(f"Successfully seeded {len(result.inserted_ids)} heritage sites from 30+ major locations.")
    client.close()

if __name__ == "__main__":
    asyncio.run(seed_heritage())
