"""
CrewAI Supervisor Agent
Uses LangChain to simulate a CrewAI-style supervisor that validates agent outputs.
"""

from typing import Dict, List, Any
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI
import os
import json

class CrewSupervisorAgent:
    """
    Supervisor Agent that acts as a Quality Assurance layer.
    
    Role:
    1. Review outputs from Personalization, Sustainability, and Itinerary agents.
    2. Check for logical inconsistencies (e.g., "Eco-friendly" trip using a private jet).
    3. Verify that constraints (budget, time) are met.
    4. Approve or Request Revision.
    """
    
    def __init__(self):
        self.name = "CrewAI Supervisor"
        self.api_key = os.getenv("GOOGLE_API_KEY")
        
        if self.api_key:
            self.llm = ChatGoogleGenerativeAI(model="gemini-pro", google_api_key=self.api_key)
        else:
            print(f"[{self.name}] Warning: GOOGLE_API_KEY not found. Running in mock mode.")
            self.llm = None

    async def audit_plan(self, plan_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Audit the proposed travel plan.
        
        Args:
            plan_data: Dictionary containing outputs from all other agents.
            
        Returns:
            Audit report with status (PASSED/FAILED) and feedback.
        """
        print(f"[{self.name}] Auditing plan for {plan_data.get('destination', 'Unknown')}...")
        
        if not self.llm:
            return self._mock_audit(plan_data)
            
        try:
            prompt = ChatPromptTemplate.from_template("""
            You are a strict Quality Assurance Supervisor for a Sustainable Travel Agency.
            Review the following travel plan generated by your team of AI agents.
            
            Plan Details:
            Destination: {destination}
            Sustainability Score: {sustainability_score}
            Carbon Footprint: {carbon_footprint}
            Itinerary: {itinerary_summary}
            
            Rules:
            1. Sustainability Score must be > 70.
            2. Transport modes should align with "Eco-Friendly" goals (minimize flights/cars).
            3. Itinerary must be logically feasible (time/distance).
            
            Output a JSON object with:
            - status: "PASSED" or "FAILED"
            - feedback: A brief explanation of your decision.
            - confidence: A score between 0.0 and 1.0.
            """)
            
            chain = prompt | self.llm | StrOutputParser()
            
            # Summarize itinerary for prompt
            itinerary_summary = json.dumps(plan_data.get('days', [])[:2]) # First 2 days to save tokens
            
            response = await chain.ainvoke({
                "destination": plan_data.get('destination'),
                "sustainability_score": plan_data.get('sustainability_score'),
                "carbon_footprint": plan_data.get('carbon_saved'),
                "itinerary_summary": itinerary_summary
            })
            
            # Clean up response to ensure valid JSON
            response = response.replace("```json", "").replace("```", "").strip()
            return json.loads(response)
            
        except Exception as e:
            print(f"[{self.name}] Audit failed: {e}")
            return self._mock_audit(plan_data)

    def _mock_audit(self, plan_data: Dict[str, Any]) -> Dict[str, Any]:
        """Fallback mock audit if LLM is unavailable"""
        score = plan_data.get('sustainability_score', 0)
        if score > 75:
            return {
                "status": "PASSED",
                "feedback": "Plan meets high sustainability standards. Transport choices are optimal.",
                "confidence": 0.98
            }
        else:
            return {
                "status": "PASSED_WITH_WARNINGS",
                "feedback": "Sustainability score is marginal. Consider swapping private car for train.",
                "confidence": 0.85
            }

# Singleton instance
crew_supervisor = CrewSupervisorAgent()
